on:
  push:
    branches:
      - master

jobs:
  run_pull:
    name: Run Pull
    runs-on: ubuntu-latest

    steps:
    - name: Install Ssh Keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Connect And Pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_PATH_TO_REPO }} && git pull && echo ${{ secrets.CERTIFICATE }} > ./nginx-module/certificate.pem && echo ${{ secrets.PRIVATEKEY }} > ./nginx-module/privatekey.pem && docker-compose build && systemctl restart ${{ secrets.SSH_COMPOSE_SERVICE }}"
    - name: Cleanup
      run: rm -rf ~/.ssh
